#!/usr/bin/env python3.4
# -*- mode: python; indent-tabs-mode: nil -*-

# mlat-server: a Mode S multilateration server
# Copyright (C) 2015  Oliver Jowett <oliver@mutability.co.uk>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import logging
import mlat.server.main
from logging.handlers import RotatingFileHandler

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO,
                        style='{',
                        format='{asctime}.{msecs:03.0f}  {levelname:8s} {name:20s} {message}',
                        datefmt='%Y%m%d %H:%M:%S')
    #################################################################################################
    #RotatingFileHandler，max 20 log files，max size of each log file is 20M
    Rthandler = RotatingFileHandler('/home/yang/MLAT/mlat-server-master/log/mlat.log', 'a', maxBytes=20*1024*1024, backupCount=20)
    Rthandler.setLevel(logging.INFO)
    formatter = logging.Formatter('%(asctime)-26s %(levelname)-8s %(name)-20s %(message)s')
    Rthandler.setFormatter(formatter)
    logging.getLogger('').addHandler(Rthandler)
    ################################################################################################

    mlat.server.main.MlatServer().run()
